#!/usr/bin/python

activate_this = 'ENV/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
from os.path import abspath

sys.path.append(abspath("src"))

from manage import settings
from django.core.management import execute_manager
execute_manager(settings)

