#!/usr/bin/python

activate_this = 'ENV/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
from os.path import abspath
import os
sys.path.append(abspath("src"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "settings")
os.chdir("src")

from django.core import management 
management.execute_from_command_line(sys.argv)